### DISCUSSION TITLE
Unable to get config to pass

### DISCUSSION THREAD

**Discussion by tom-hooper** [klaasnicolaas/home-assistant-glow#134] [Q&A] [answered]
Hi all, 

I'm struggling to get the yaml config to compile and flash. 

```yaml
tom@Laptop:/PATH_TO_YOUR_CONFIG$ esphome home_assistant_glow.yaml config
INFO Reading configuration home_assistant_glow.yaml...
INFO Detected timezone 'AEST' with UTC offset 10 and daylight savings time from 02 October 02:00:00 to 02 April 03:00
Failed config

dashboard_import: [source home_assistant_glow.yaml:22]

  Component not found: dashboard_import.
  package_import_url: github://klaasnicolaas/home-assistant-glow/home_assistant_glow.yaml
esphome: None
  name: home-assistant-glow
  comment: Measure your energy consumption with the pulse LED on your smart meter

  [project] is an invalid option for [esphome]. Please check the indentation.
  project:  None
    name: klaasnicolaas.home_assistant_glow
    version: 3.0.0
  platform: ESP32
  board: nodemcu-32s
improv_serial: [source home_assistant_glow.yaml:48]

  Component not found: improv_serial.
api: [source home_assistant_glow.yaml:52]
  services:  [source home_assistant_glow.yaml:53]
    - [source home_assistant_glow.yaml:53]
      service: reset_total_energy
      then:  [source home_assistant_glow.yaml:55]
        - [source home_assistant_glow.yaml:55]

          Unable to find action with the name 'button.press'.
          button.press:  [source home_assistant_glow.yaml:56]
            id: button_reset_total
button: [source home_assistant_glow.yaml:94]

  Component not found: button.
  - platform: restart
    name: Restart - Glow
  - platform: template
    name: Reset - Total Energy
    id: button_reset_total
    on_press:
      - pulse_meter.set_total_pulses:
          id: sensor_energy_pulse_meter
          value: 0
sensor.pulse_meter: [source home_assistant_glow.yaml:124]
  platform: pulse_meter
  name: House - Power Consumption
  id: sensor_energy_pulse_meter
  unit_of_measurement: W

  [state_class] is an invalid option for [sensor.pulse_meter]. Did you mean [state_topic], [device_class]?
  state_class: measurement [source home_assistant_glow.yaml:128]
  device_class: power
  icon: mdi:flash-outline
  accuracy_decimals: 0
  pin: GPIO12
  on_value:
    then:
      - light.turn_on:
          id: led_red
      - delay: 0.5s
      - light.turn_off:
          id: led_red
  filters:
    - lambda: return x * ((60.0 / 1) * 1000.0);
  total:  [source home_assistant_glow.yaml:146]
    name: House - Total Energy
    id: sensor_total_energy
    unit_of_measurement: kWh
    icon: mdi:circle-slice-3

    [state_class] is an invalid option for [total]. Did you mean [state_topic], [device_class]?
    state_class: total_increasing [source home_assistant_glow.yaml:150]
    device_class: energy
    accuracy_decimals: 3
    filters:
      - lambda: return x * (1.0 / 1);
sensor.total_daily_energy: [source home_assistant_glow.yaml:158]
  platform: total_daily_energy
  name: House - Daily Energy
  id: sensor_total_daily_energy
  power_id: sensor_energy_pulse_meter
  unit_of_measurement: kWh
  icon: mdi:circle-slice-3

  [state_class] is an invalid option for [sensor.total_daily_energy]. Did you mean [state_topic], [device_class]?
  state_class: total_increasing [source home_assistant_glow.yaml:164]
  device_class: energy
  accuracy_decimals: 3
  filters:
    - multiply: 0.001
tom@Laptop:/PATH_TO_YOUR_CONFIG$
```

Getting lots of **component not found** errors

any advice?
