### DISCUSSION TITLE
Multiple meters with a single ESP32 NodeMCU

### DISCUSSION THREAD

**Discussion by tauzahmd** [klaasnicolaas/home-assistant-glow#175] [General]
I just wanted to understand if I have multiple meters can I just go ahead and define the ``-platform`` section under ``sensor`` in YAML for the remaining meters' photosensor (by selecting different pins for each photosensor) and it should work out of the box?

PS: I am new to HA and still understanding the YAML type flashing the software.

**Comment by klaasnicolaas** [comment]
If you use the pulse_meter platform sensor several times with different IDs, you could theoretically read several meters. Personally, however, I have never tried it.

**Reply by tauzahmd** [reply]
I m working on using it for monitoring my three meters, let me try it out and update it here.

**Reply by klaasnicolaas** [reply]
Any update so far on run multiple meters on a single ESP?

**Reply by wwwebrat** [reply]
> I m working on using it for monitoring my three meters, let me try it out and update it here.

What was the result? I have two separate meters and would be interested in your insights.

**Comment by xsaMNJfkltrwq5r3** [comment]
I have a similar issue where my smart meter has two individual pulse LED ouputs, one for importing and the other for exporting.  So I am hoping that I can do exactly this.

**Comment by xsaMNJfkltrwq5r3** [comment]
I just duplicated the instances of the sensors, on the esp and in the config  renamed them accordingly and it seems to work fine.On 12 Dec 2022 17:31, Webrat ***@***.***> wrote:

I m working on using it for monitoring my three meters, let me try it out and update it here.

What was the result? I have two separate meters and would be interested in your insights.

**Reply by razsultana** [reply]
I have exactly the same situation - one meter with two pulsing LEDs, one for import from the grid, one for export to the grid.
It sounds like you solved this problem with one ESP32 and two photosensors. 
Could you share which additional pin you used to attach the additional photosensor, i.e. if you used GPIO13 for the first one, which GPIO pin you used for the second one?
I am just learning ESP32 and just looking here https://randomnerdtutorials.com/esp32-pinout-reference-gpios/ it sounds like you could use GPIO12, GPIO14 or GPIO15 as they don't seem to be used by anything else and they are also part of ADC2, just different channels.
Any input would be appreciated. Thanks!

**Reply by xsaMNJfkltrwq5r3** [reply]
Hello, so under the sensor: description you can just add the individual inputs.  Call them what you want and assign them to your chosen inputs.  For me I went with GPIO25 & 26 for no reason other than they appeared to do the job.  I have done exactly this setup and I have been using it with home assistant for ages with no issues.  Let me know if you need any further clarification.



# Pulse meter1
  - platform: pulse_meter
    name: '${friendly_name} - Imported Power Consumption'
    id: sensor_energy_pulse_meter1
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin1}
    internal_filter: 200ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Imported Energy'
      id: sensor_total_energy1
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});

  # Pulse meter2
  - platform: pulse_meter
    name: '${friendly_name} - Exported Power Consumption'
    id: sensor_energy_pulse_meter2
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin2}
    internal_filter: 200ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Exported Energy'
      id: sensor_total_energy2
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});

**Reply by razsultana** [reply]
Thank you for the prompt reply!
Your shared experience is much appreciated.
I think the github comments processor  has messed up your yaml code, interpreting it as markdown code.
I'm assuming the yaml code was as such (you can put three backticks on a line before and after the yaml code, with the word `yaml` following the three backticks on the line before the code to show it like below):
```yaml
sensor: 

  # Pulse meter1
  - platform: pulse_meter
    name: '${friendly_name} - Imported Power Consumption'
    id: sensor_energy_pulse_meter1
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin1}
    # internal_filter: 200ms
    on_value:
      then:
        - light.turn_on:
          id: led_red
        - delay: 0.5s
        - light.turn_off:
          id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Imported Energy'
      id: sensor_total_energy1
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});

  # Pulse meter2
  - platform: pulse_meter
    name: '${friendly_name} - Exported Power Consumption'
    id: sensor_energy_pulse_meter2
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin2}
    # internal_filter: 200ms
    on_value:
    then:
      - light.turn_on:
        id: led_red
      - delay: 0.5s
      - light.turn_off:
        id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      #  - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);

    total:
      name: '${friendly_name} - Total Exported Energy'
      id: sensor_total_energy2
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});

```
Could you confirm this was the code in your config?
Many thanks.
