### DISCUSSION TITLE
Trouble with Install

### DISCUSSION THREAD

**Discussion by Clarke44** [klaasnicolaas/home-assistant-glow#332] [Q&A] [answered]
Hi ,

Trying to install on a ESP32. I have copied the esp32.yaml into the homeassistant ESPHome folder, if I try and install or validate the code I get the below error? 

not sure what I'm doing wrong. 

`INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/home-assistant-glow.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Error reading file /config/esphome/../components/basis.yaml: [Errno 2] No such file or directory: '/config/esphome/../components/basis.yaml'`

**Comment by KixMan28** [comment, marked as answer]
Hi @Clarke44 ! I think you need to copy the "Components" folder with its content to the "esphome" folder, where you already copied the "esp32.yaml" file, because the esp32.yaml file contains "!include" commands pointing to the files in the "components" folder.

```
packages:
  basis: !include ../components/basis.yaml
  status_led: !include ../components/status_led.yaml
  pulse_meter: !include ../components/pulse_meter.yaml
```
The setup description explains the old way of installing the files, when all the yaml was contained in one file (home_assistant_glow.yaml). 

If it still doesn't work, then move the "components" folder one level up in the config folder
