### DISCUSSION TITLE
Persistent values for sensor_total_energy and total_daily_energy

### DISCUSSION THREAD

**Discussion by ojwc** [klaasnicolaas/home-assistant-glow#522] [Ideas]
Values for total kWh can be written to flash, so they can be restored after a reboot.

For total_daily_energy this is straightforward, just add to the config:
`restore: True`

For sensor_total_energy it is a little more complicated as there isn't any `restore:` flag defined. Define a global variable:
````
 globals:
  id: total_consumption
  type: float
  restore_value: True
````

Limit the frequency ESPHome will write to flash, to reduce wear on flash memory:
```
 preferences:
  flash_write_interval: 5min # or whatever value is preferred, it should be a long perio
```

Change the `filters:` section in `total:` part of `pulse_meter` to make the global variable equal to `sensor_total_energy`:
```
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: id(total_consumption) = id(sensor_total_energy).raw_state;
            return x * (1.0 / id(select_pulse_rate).state);

```
Finally to restore the total after boot, add `on_boot` flag to `esphome:`
```
  on_boot: 
    then:
      - pulse_meter.set_total_pulses: 
          id: sensor_energy_pulse_meter
          value: !lambda "return id(total_consumption);"
```

Now `sensor_total_energy` can be set to match the meter total and it will persist between reboots, as will `total_daily_energy`. Take care with ESP8266 as it has limitations for flash storage. Tested and working on ESP32 (nodemcu-32s).
