### DISCUSSION TITLE
ESP32 dont seem to follow the yaml.

### DISCUSSION THREAD

**Discussion by tarlih94** [klaasnicolaas/home-assistant-glow#612] [Q&A]
When i put on filters or edit enything in the sensor part of the yaml, it does not go into effect. not even after rebooting the esp. Can any of you see any wrong in my yaml that makes it not listen to it? it connect and reads the led. Though best i can adjust sensitivity between read and not read the led is so that it counts 1 pulse 2-3 times. I wanted to corrigate that with internal filter but it doesnt change any behaiour no matter what i try in the yaml. i use the 38 pin esp32

```yaml
sensor:
  # Pulse meter
  - platform: pulse_meter
    id: sensor_energy_pulse_meter
    name: '${Glow} - Power Consumption'
    pin: GPIO26
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    on_raw_value:
    internal_filter_mode: PULSE
    internal_filter: 250ms
```
