### ISSUE TITLE
Not registering anything?

### ISSUE THREAD

**Issue by thehiddentruth** [klaasnicolaas/home-assistant-glow#102]
I'm trying to understand, why it's not registering any data.

When I use my phones flash to trigger the photodiode, the D0 led blinks, but nothing gets registeret, neither in the logs nor in HA.

**Setup looks like this**
- Wemos D1 Mini Lite
- 3.3V -> VCC
- GND -> GND
- D2 -> D0

**My ESPHome yaml looks like this**

```yaml
substitutions:
  device_name: energy
  friendly_name: House
  device_description: "Measure your energy consumption with the pulse LED on your smart meter"
  pulse_pin: GPIO4
  status_led: GPIO5


  pulse_rate: '1000'


  web_username: 'glow'
  web_password: 'esphome'

esphome:
  name: '${device_name}'

esp8266:
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: gpio
    pin: GPIO2
    id: output_red
  - platform: gpio
    pin: GPIO4
    id: output_green

light:
  - platform: binary
    internal: true
    id: led_red
    name: Red
    output: output_red

status_led:
  pin:
    number: ${status_led}

text_sensor:
  - platform: version
    hide_timestamp: true
    name: '${friendly_name} - ESPHome Version'
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} - IP Address'
      icon: mdi:wifi
    ssid:
      name: '${friendly_name} - Connected SSID'
      icon: mdi:wifi-strength-2

sensor:
  - platform: pulse_meter
    id: energy_pulse_meter
    name: '${friendly_name} - Power consumption'
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total energy'
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        - lambda: return x * (1.0 / ${pulse_rate});
```

Any idea why nothing gets registered?
