### ISSUE TITLE
Power Consumption very low? Reasons?

### ISSUE THREAD

**Issue by snipah** [klaasnicolaas/home-assistant-glow#115]
Hi and thanks for your brilliant work on this one! I built this a proposed and I seems to work just fine: Values seems to be consistent at first glance in the range between 160 - 280 watts. My problem: Even when using the water boiler or the electric stove, consumption goes up but never reaches expected values. Am I interpreting the values in a wrong way? Is this current consumtion per second or does the period of time vary in which this amount of energy in being consumed?

My meter is an eHZ-IW8 with 10.000 imp./kWh. The configuration is amended accordingly

```yaml
substitutions:
  device_name: home-assistant-glow
  friendly_name: House
  device_description: "Measure your energy consumption with the pulse LED on your smart meter"
  pulse_pin: GPIO12
  status_led: GPIO5

  imp/kWh rate ⬇ #
  pulse_rate: '10000.0'

  Webserver credentials ⬇ #
  web_username: 'snip'
  web_password: 'snap'

dashboard_import:
  package_import_url: github://klaasnicolaas/home-assistant-glow/home_assistant_glow.yaml

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  project:
    name: "klaasnicolaas.home_assistant_glow"
    version: "3.0.0"
  platform: ESP8266
  board: nodemcuv2

WiFi credentials #
wifi:
  ssid: 'snip-snap'       # Enter your WiFi SSID here. Example: `ssid: 'your_network_name'`
  password: 'snap-snip'   # Enter your wifi password here. Example: `password: 'abcde123456'`

  Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
   ssid: '${device_name}'

captive_portal:

Enable logging
logger:

Enable improv over serial
improv_serial:

Enable Home Assistant API
api:
  services:
    - service: reset_total_energy
      then:
        - button.press:
            id: button_reset_total

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

web_server:
  port: 80
  auth:
    username: '${web_username}'
    password: '${web_password}'

output:
 #-# platform: gpio
    #pin: GPIO5
    #id: output_blue
  - platform: gpio
    pin: GPIO2
    id: output_red
  - platform: gpio
    pin: GPIO4
    id: output_green

light:
  - platform: binary
    internal: true
    id: led_red
    name: Red
    output: output_red

Status LED for connection
status_led:
  pin:
    # Blue LED
    number: ${status_led}

button:
  - platform: restart
    name: "Restart - Glow"
  - platform: template
    name: "Reset - Total Energy"
    id: button_reset_total
    on_press:
      - pulse_meter.set_total_pulses:
          id: sensor_energy_pulse_meter
          value: 0

Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    hide_timestamp: true
    name: '${friendly_name} - ESPHome Version'
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} - IP Address'
      icon: mdi:wifi
    ssid:
      name: '${friendly_name} - Connected SSID'
      icon: mdi:wifi-strength-2

sensor:
 WiFi signal
  - platform: wifi_signal
    name: "${friendly_name} - WiFi Signal"
    update_interval: 120s

 Pulse meter
  - platform: pulse_meter
    name: '${friendly_name} - Power Consumption'
    id: sensor_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    internal_filter: 100ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.05s
        - light.turn_off:
            id: led_red
    filters:
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Energy'
      id: sensor_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        - lambda: return x * (1.0 / ${pulse_rate});
   Total day useage
  - platform: total_daily_energy
    name: '${friendly_name} - Daily Energy'
    id: sensor_total_daily_energy
    power_id: sensor_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

Enable time component to reset energy at midnight
time:
  - platform: sntp
    id: my_time`
```

The logs looks like this: 
`[16:25:13][D][light:046]:   State: ON
[16:25:13][D][sensor:113]: 'House - Daily Energy': Sending state 0.16024 kWh with 3 decimals of accuracy
[16:25:13][D][sensor:113]: 'House - Total Energy': Sending state 3.20060 kWh with 3 decimals of accuracy
[16:25:13][D][light:035]: 'Red' Setting:
[16:25:13][D][light:046]:   State: OFF
[16:25:14][D][sensor:113]: 'House - Power Consumption': Sending state 239.84010 W with 0 decimals of accuracy
[16:25:14][D][light:035]: 'Red' Setting:
[16:25:14][D][light:046]:   State: ON
[16:25:14][D][sensor:113]: 'House - Daily Energy': Sending state 0.16024 kWh with 3 decimals of accuracy
[16:25:14][D][sensor:113]: 'House - Total Energy': Sending state 3.20070 kWh with 3 decimals of accuracy
[16:25:14][D][light:035]: 'Red' Setting:
[16:25:14][D][light:046]:   State: OFF
[16:25:16][D][sensor:113]: 'House - Power Consumption': Sending state 243.24323 W with 0 decimals of accuracy
[16:25:16][D][light:035]: 'Red' Setting:
[16:25:16][D][light:046]:   State: ON
[16:25:16][D][sensor:113]: 'House - Daily Energy': Sending state 0.16025 kWh with 3 decimals of accuracy
[16:25:16][D][sensor:113]: 'House - Total Energy': Sending state 3.20080 kWh with 3 decimals of accuracy
[16:25:16][D][light:035]: 'Red' Setting:
[16:25:16][D][light:046]:   State: OFF
[16:25:17][D][sensor:113]: 'House - Power Consumption': Sending state 244.89795 W with 0 decimals of accuracy
[16:25:17][D][light:035]: 'Red' Setting:
[16:25:17][D][light:046]:   State: ON
[16:25:17][D][sensor:113]: 'House - Daily Energy': Sending state 0.16025 kWh with 3 decimals of accuracy
[16:25:17][D][sensor:113]: 'House - Total Energy': Sending state 3.20090 kWh with 3 decimals of accuracy
[16:25:17][D][light:035]: 'Red' Setting:
[16:25:17][D][light:046]:   State: OFF
[16:25:18][D][sensor:113]: 'House - Power Consumption': Sending state 245.06467 W with 0 decimals of accuracy
[16:25:18][D][light:035]: 'Red' Setting:
[16:25:18][D][light:046]:   State: ON
[16:25:18][D][sensor:113]: 'House - Daily Energy': Sending state 0.16026 kWh with 3 decimals of accuracy
[16:25:18][D][sensor:113]: 'House - Total Energy': Sending state 3.20100 kWh with 3 decimals of accuracy
[16:25:19][D][light:035]: 'Red' Setting:
[16:25:19][D][light:046]:   State: OFF
[16:25:20][D][sensor:113]: 'House - Power Consumption': Sending state 243.07901 W with 0 decimals of accuracy
[16:25:20][D][light:035]: 'Red' Setting:
[16:25:20][D][light:046]:   State: ON
[16:25:20][D][sensor:113]: 'House - Daily Energy': Sending state 0.16026 kWh with 3 decimals of accuracy
[16:25:20][D][sensor:113]: 'House - Total Energy': Sending state 3.20110 kWh with 3 decimals of accuracy
[16:25:20][D][light:035]: 'Red' Setting:
[16:25:20][D][light:046]:   State: OFF
[16:25:21][D][sensor:113]: 'House - Power Consumption': Sending state 240.16010 W with 0 decimals of accuracy
[16:25:21][D][light:035]: 'Red' Setting:
[16:25:21][D][light:046]:   State: ON
[16:25:21][D][sensor:113]: 'House - Daily Energy': Sending state 0.16027 kWh with 3 decimals of accuracy
[16:25:21][D][sensor:113]: 'House - Total Energy': Sending state 3.20120 kWh with 3 decimals of accuracy
[16:25:22][D][light:035]: 'Red' Setting:
[16:25:22][D][light:046]:   State: OFF
[16:25:23][D][sensor:113]: 'House - Power Consumption': Sending state 245.06467 W with 0 decimals of accuracy
[16:25:23][D][light:035]: 'Red' Setting:
[16:25:23][D][light:046]:   State: ON
[16:25:23][D][sensor:113]: 'House - Daily Energy': Sending state 0.16027 kWh with 3 decimals of accuracy
[16:25:23][D][sensor:113]: 'House - Total Energy': Sending state 3.20130 kWh with 3 decimals of accuracy
[16:25:23][D][light:035]: 'Red' Setting:`
