### ISSUE TITLE
Add Uptime Sensor

### ISSUE THREAD

**Issue by pschneider87** [klaasnicolaas/home-assistant-glow#139]
I find it useful to have an Uptime Sensor in HA Glow. I've copied right away from the ESPHome-Page from the ["Human readable sensor" Section](https://esphome.io/components/sensor/uptime.html#human-readable-sensor)

I'm not so familiar with GitHub, so I'm afraid I can't make a PR :-/
But maybe somebody can quickly copy/paste it into the project, is quite nice to know about it:

<img width="176" alt="image" src="https://user-images.githubusercontent.com/17707309/156612662-1e3b67ef-a948-458f-8ba9-8153dcd7b57e.png">

**Comment by pschneider87** [comment]
added https://github.com/klaasnicolaas/home-assistant-glow/pull/142
don't know if @klaasnicolaas needs to do something to make the tests verify the code :-/

**Comment by klaasnicolaas** [comment]
What about this uptime sensor: https://github.com/klaasnicolaas/smarty-homeassistant-config/blob/master/esphome/sensors/uptime_timestamp.yaml

**Comment by pschneider87** [comment]
I'll give that a try. The idea sounds good to only send it once.

**Comment by klaasnicolaas** [comment]
And?

**Comment by klaasnicolaas** [comment]
Still something that is on my list to add 🤔

**Comment by mcchots** [comment]
Doesn't this [uptime sensor](https://esphome.io/components/sensor/uptime.html) solve this issue?

**Comment by jessereynolds** [comment]
Yep, I've been using the uptime sensor @mcchots mentions with success. Added the following to the esphome build definition yaml file: 

```
  - platform: uptime
    name: Uptime
    id: sensor_uptime
    update_interval: 60s
```

**Comment by spanznet** [comment]
Uptime is great, but rather than have to calculate backwards in time to work out when it last booted, I prefer to add one that updates once on each boot when the time syncs:

```
text_sensor:
  - platform: template
    name: "Last Boot"
    id: device_last_boot
    icon: mdi:clock
    entity_category: diagnostic

time:
  - platform: homeassistant
    timezone: "Australia/Hobart"
    id: homeassistant_time
    on_time_sync:
      then:
        - if:
            condition:
              lambda: 'return id(device_last_boot).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_boot
                  state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
```

Which gives you:

![image](https://github.com/klaasnicolaas/home-assistant-glow/assets/35336403/a9341905-05e8-4e28-8cd4-4124241d1e9e)
