### ISSUE TITLE
Daily Energy doesn't reset

### ISSUE THREAD

**Issue by srslykev** [klaasnicolaas/home-assistant-glow#140]
Hi there, 
so far, everything is working great except the daily energy meter. It won't reset at midnight. I'm using the regular code with no changes apart from the led on pulse part:
 
```
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
```

Any idea what could be wrong?
