### ISSUE TITLE
Every other power consumption reading is 0W.

### ISSUE THREAD

**Issue by bgmn** [klaasnicolaas/home-assistant-glow#17]
Every other power consumption reading is 0 W. I can see that the photodiode works correctly from its led and it flashes just like the led on the power meter. I have a meter that has 10000 impulses per 1 kWh.

I have shortened the config because i have no need for the leds or web server.

```
#
substitutions:
  device_name: home_assistant_glow
  friendly_name: House
  device_description: "Measure your energy consumption with the pulse LED on your smart meter"
  pulse_pin: GPIO12

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  project:
    name: "klaasnicolaas.home_assistant_glow"
    version: "1.1.2"
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "redblock"
  password: "si(ni2neb3fanhGEe!vo4neGna"
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}'
    password: "luVL44uRRwpW"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "asidna3tq3t9ah2A)RF#HA9ah3fa"

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

sensor:
  - platform: pulse_meter
    internal_filter: 8us
    name: '${friendly_name} - Power consumption'
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    filters:
      # multiply value = (60 / imp value) * 1000
      - multiply: 6
    total:
      name: '${friendly_name} - Total energy'
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      last_reset_type: auto
      state_class: measurement
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        - multiply: 0.0001`
```
