### ISSUE TITLE
Daily Energy resets at 2am

### ISSUE THREAD

**Issue by julian100004** [klaasnicolaas/home-assistant-glow#204]
The time in the logs is correct, but the daily energy sensor resets every day at 2 a.m. Could someone perhaps help me out here?

**Comment by klaasnicolaas** [comment]
Which time platform do you use?

https://esphome.io/components/time.html#home-assistant-time-source

**Comment by julian100004** [comment]
Should be homeassistant, since i didn't change it when first flashing the esp.
I tried setting it to sntp, so my file would look like this:

```yaml
substitutions:
  name: home-assistant-glow
packages:
  klaasnicolaas.home-assistant-glow: github://klaasnicolaas/home-assistant-glow/home_assistant_glow.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false

time:
  - platform: sntp
    id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
````
but whenever i try to flash it wirelessly with the esphome ha integration, i run into errors while it's compiling everything.

**Comment by klaasnicolaas** [comment]
Was this already resolved?

**Comment by julian100004** [comment]
Sadly not

**Comment by klaasnicolaas** [comment]
But are you using the `homeassistant` or the `sntp` time component?

**Comment by julian100004** [comment]
I'm trying to figure that out, but i don't know how.
I'm currently trying my way around with esphome, but everything i do just gives me some error.
It probably is still set to homeassistant. So that will probably be the problem. But i have no clue how i can set it to sntp.

**Comment by klaasnicolaas** [comment]
You can find that in the yaml file that you used in your own esphome environment for the HA Glow 😉 Maybe you can share what errors you get? Otherwise I can't do much for you to think about how we solve your problem.

> But i have no clue how i can set it to sntp.

Sure? You have already posted the code for that 😉 

```yaml
time:
  - platform: sntp
    id: sntp_time
```
