### ISSUE TITLE
Current Consumption and "Electricity Meter Reading"

### ISSUE THREAD

**Issue by Zodiac-69** [klaasnicolaas/home-assistant-glow#254]
The formula for Current Consumption - return x * ((60.0 / id(electricity_pulse_rate)) * 1000.0) - did not work for me, it seemed to be out by a factor of 1000.
I used puse rate of 1000/kWh in the global - electricity_pulse_rate
Using this - return x * (3600/60.0) - worked for me

How can i make the "Electricity Meter Reading" count "Down" instead of up.
I want to use it as a Pre-Pay value and subtract from the credit (kWh) i have instead of counting up (Accumulating)

**Comment by klaasnicolaas** [comment]
Weird that the formula doesn't work, because whether you do 3600 / 60 or (60 / 1000) * 1000, both come out at 60. Can you share your used yaml code and what your logs measure?

**Comment by Zodiac-69** [comment]
I have implemented your code, except for the "GAS" as i only have electricity meter here in South Africa.
The rest is the same using the electricity part only..

# Electricity Pulse meter
  - platform: pulse_meter
    name: 'Current ${friendly_name}'
    id: sensor_electricity_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin_electricity}
    # internal_filter: 100ms
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      # "below lambda" - return x * ((60.0 / id(electricity_pulse_rate)) * 1000.0);
      - lambda: |-
          return x * (3600/60.0);

**Comment by klaasnicolaas** [comment]
> except for the "GAS"

There is no official support for this at all, unless someone else has modified the code for it 😉 

Do you also have this in your yaml code?
```yaml
number:
  # Select the correct pulse rate for your meter
  - platform: template
    id: select_pulse_rate
    name: 'Puls rate - imp/kWh'
    optimistic: true
    mode: box
    min_value: 100
    max_value: 10000
    step: 100
    restore_value: yes
    initial_value: 1000
```
