### ISSUE TITLE
Daily Energy v. Total Energy

### ISSUE THREAD

**Issue by droopycool** [klaasnicolaas/home-assistant-glow#270]
Hi, I managed everything working and I think it's great. My only issue is that the "Total Energy" values are not matching the "Daily Energy" ones.

Total energy matches perfectly with the consumption my meter shows, Daily Energy seems to be growing at a much faster rate and not matching or even proportional to the total energy. 

Attached my code (at least the part I think it's relevant) and some captures of the values. Can anybody help me to spot where the issue is?

```

  # Pulse meter
  - platform: pulse_meter
    name: '${friendly_name} - Power Consumption'
    id: sensor_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    #internal_filter: 100ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / id(select_pulse_rate).state) * 1000.0);
    total:
      name: '${friendly_name} - Total Energy'
      id: sensor_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-7
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / id(select_pulse_rate).state);
  # Total day useage
  - platform: total_daily_energy
    name: '${friendly_name} - Daily Energy'
    id: sensor_total_daily_energy
    power_id: sensor_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

# Enable time component to reset energy at midnight
# https://esphome.io/components/time/homeassistant.html
time:
  - platform: homeassistant
    id: homeassistant_time

```

![Screenshot 2023-01-25 080840](https://user-images.githubusercontent.com/87247848/214501870-01a98807-ae00-454c-bd06-86d7b06e842e.png)

![Screenshot 2023-01-25 080906](https://user-images.githubusercontent.com/87247848/214501884-3e9c77aa-c554-4e44-a4b7-bcab37e86aee.png)
