### ISSUE TITLE
Spikes on switch over of solar and electric

### ISSUE THREAD

**Issue by ANDuff** [klaasnicolaas/home-assistant-glow#284]
I have two of these setup one on my electric and one on my solar panels:
![image](https://user-images.githubusercontent.com/11334104/233337413-acb9dc9c-ced7-42cb-b1ba-2a4b8d185a23.png)

As you can see my current import is 0 however if I started to import again I would get a sudden jump in the daily energy amount that looks something like this: 
![image](https://user-images.githubusercontent.com/11334104/233337662-11931b97-8829-4ca0-8526-86d89d51625d.png)
So there are around 3 of them in that image, 19April at 12pm, around 6pm and then 20 April at around 10am. The same happens for the solar when it first starts generating for the day there is a jump.

I am wondering how to stop these spikes from occurring. Any help would be greatly appreciated.

My setup looks like this:
```
 - platform: pulse_meter
    name: '${friendly_name} - Power Consumption'
    id: sensor_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    timeout: 120 sec
    internal_filter: 50ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Energy'
      id: sensor_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});
  # Total day useage
  - platform: total_daily_energy
    name: '${friendly_name} - Daily Energy'
    id: sensor_total_daily_energy
    power_id: sensor_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
   ```
