### ISSUE TITLE
Suggestions for updating readme

### ISSUE THREAD

**Issue by DavidREWorthington** [klaasnicolaas/home-assistant-glow#39]
I've got this working now but I would have found it easier with the following pointers so these are documentation suggestions that might help others;

- show how to bend the sensor to fit the 3D case ( I know this must seem obvious but I scratched my head worrying I'd got the wrong component for a bit)
- mention the need to adjust the sensitivity of the photodiode to suit the meter led. I found one of the meters much darker than the other and this took several adjustments to get it working
- mention that it is possible to use 2 glow sensors if your solar meter also has a pulse led and integrate this with the Energy dashboard

I found the pulse_meter behaved strangely with the solar meter. I switched to use pulse_counter and it seems to be stable if slower to update - I guess it updates at a lower frequency

I defined an additional pin (I use 13) as solar_pin

great work by the way - I now have a working HA Energy dashboard working for the cost of a few sensors!

Extract from my yaml

```
sensor:
  - platform: pulse_meter #counter
    name: '${friendly_name} - Power consumption'
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    on_value:
      then:
        - light.turn_on:
            id: led_red
            flash_length: 400ms
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total energy'
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      last_reset_type: auto
      state_class: measurement
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});
  - platform: pulse_counter
    name: '${friendly_name} - Solar production'
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${solar_pin}
    on_value:
      then:
        - light.turn_on:
            id: led_red
            flash_length: 400ms
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total solar'
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      last_reset_type: auto
      state_class: measurement
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulse_rate});        
```
