### ISSUE TITLE
Power consumption "spam"?

### ISSUE THREAD

**Issue by getninjaN** [klaasnicolaas/home-assistant-glow#536]
Firstly, not sure what title to set. Sorry 'bout that.

My Glow has started acting up.
Updated to the latest version through the website after a Home Assistant update which renamed something, or something, and now the consumption has gone haywire.
Any ideas?
All the components are the recommended once in the README here on GitHub.

I tried changing the `internal_filter` setting but not sure if that made a difference.

https://github.com/user-attachments/assets/4e18779f-51f4-46cf-9761-e67c127f4d91

**Comment by klaasnicolaas** [comment]
Can you also show your yaml config? Or the adjustments you made?

**Comment by getninjaN** [comment]
> Can you also show your yaml config? Or the adjustments you made?

Ofc. This is my `home-assistant-glow-e7d3b4.yaml` file. Is this the one you need?
The thing I added was `internal_filter: 100ms` after it went crazy.

```yaml
substitutions:
  name: home-assistant-glow-e7d3b4
packages:
  klaasnicolaas.home-assistant-glow: github://klaasnicolaas/home-assistant-glow/home-assistant-glow/esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: <key>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - id: !extend sensor_energy_pulse_meter
    internal_filter: 100ms
```
